apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: claude-conductor-network-policy
  namespace: claude-conductor
  labels:
    app.kubernetes.io/name: claude-conductor
    app.kubernetes.io/component: network-security
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: claude-conductor
  policyTypes:
  - Ingress
  - Egress
  
  # Ingress rules - restrict incoming traffic
  ingress:
  # Allow traffic from other claude-conductor pods
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: claude-conductor
    ports:
    - protocol: TCP
      port: 8080  # Dashboard
    - protocol: TCP
      port: 8081  # API
  
  # Allow ingress controller traffic (for external access)
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: 8080
  
  # Egress rules - restrict outgoing traffic
  egress:
  # Allow communication within namespace
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: claude-conductor
    ports:
    - protocol: TCP
      port: 8080
    - protocol: TCP
      port: 8081
  
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  
  # Allow HTTPS outbound for external APIs (if needed)
  - to: []
    ports:
    - protocol: TCP
      port: 443
  
  # Allow NTP for time synchronization
  - to: []
    ports:
    - protocol: UDP
      port: 123

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: claude-conductor-agent-network-policy
  namespace: claude-conductor
  labels:
    app.kubernetes.io/name: claude-conductor
    app.kubernetes.io/component: agent-network-security
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: claude-conductor
      app.kubernetes.io/component: agent
  policyTypes:
  - Ingress
  - Egress
  
  # Ingress rules for agents - very restrictive
  ingress:
  # Only allow traffic from orchestrator
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: claude-conductor
          app.kubernetes.io/component: orchestrator
  
  # Egress rules for agents
  egress:
  # Allow communication with orchestrator
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: claude-conductor
          app.kubernetes.io/component: orchestrator
    ports:
    - protocol: TCP
      port: 8081
  
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  
  # Allow minimal HTTPS for Claude API (if needed)
  - to: []
    ports:
    - protocol: TCP
      port: 443

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: claude-conductor
  labels:
    app.kubernetes.io/name: claude-conductor
    app.kubernetes.io/component: default-security
spec:
  podSelector: {}  # Apply to all pods in namespace
  policyTypes:
  - Ingress
  - Egress
  # No rules defined = deny all traffic by default