apiVersion: v1
kind: ServiceAccount
metadata:
  name: claude-conductor
  namespace: claude-conductor
  labels:
    app.kubernetes.io/name: claude-conductor
    app.kubernetes.io/component: orchestrator
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: claude-conductor-agent
  namespace: claude-conductor
  labels:
    app.kubernetes.io/name: claude-conductor
    app.kubernetes.io/component: agent
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: claude-conductor-orchestrator
  labels:
    app.kubernetes.io/name: claude-conductor
    app.kubernetes.io/component: orchestrator
rules:
# Restricted pod management - only for claude-conductor pods
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
  resourceNames: []  # Will be restricted by namespace
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]
# Read-only service access
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]
# Read-only ConfigMap access (no secrets for security)
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
# Limited deployment management - only for agent scaling
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "patch"]
  resourceNames: ["claude-conductor-agents"]  # Only specific deployment
# Read-only events for monitoring
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list"]
# Restricted metrics access
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: claude-conductor-agent
  labels:
    app.kubernetes.io/name: claude-conductor
    app.kubernetes.io/component: agent
rules:
# Basic pod information
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
# ConfigMap access for configuration
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
# Secret access for credentials
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
# Service discovery
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list", "watch"]
# Events for logging
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: claude-conductor-orchestrator
  labels:
    app.kubernetes.io/name: claude-conductor
    app.kubernetes.io/component: orchestrator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: claude-conductor-orchestrator
subjects:
- kind: ServiceAccount
  name: claude-conductor
  namespace: claude-conductor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: claude-conductor-agent
  labels:
    app.kubernetes.io/name: claude-conductor
    app.kubernetes.io/component: agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: claude-conductor-agent
subjects:
- kind: ServiceAccount
  name: claude-conductor-agent
  namespace: claude-conductor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: claude-conductor-namespace
  namespace: claude-conductor
  labels:
    app.kubernetes.io/name: claude-conductor
rules:
# Full access within the namespace
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["networking.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: claude-conductor-namespace
  namespace: claude-conductor
  labels:
    app.kubernetes.io/name: claude-conductor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: claude-conductor-namespace
subjects:
- kind: ServiceAccount
  name: claude-conductor
  namespace: claude-conductor
- kind: ServiceAccount
  name: claude-conductor-agent
  namespace: claude-conductor