apiVersion: v1
kind: ServiceAccount
metadata:
  name: claude-conductor
  namespace: claude-conductor
  labels:
    app.kubernetes.io/name: claude-conductor
    app.kubernetes.io/component: orchestrator
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: claude-conductor-agent
  namespace: claude-conductor
  labels:
    app.kubernetes.io/name: claude-conductor
    app.kubernetes.io/component: agent
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: claude-conductor-orchestrator
  labels:
    app.kubernetes.io/name: claude-conductor
    app.kubernetes.io/component: orchestrator
rules:
# Pod management permissions
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]
# Service management
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
# ConfigMap and Secret access
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
# Deployment management for dynamic agent scaling
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# StatefulSet management (if using stateful agents)
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# Events for logging and monitoring
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch", "create"]
# Node information for resource management
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
# Metrics access
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: claude-conductor-agent
  labels:
    app.kubernetes.io/name: claude-conductor
    app.kubernetes.io/component: agent
rules:
# Basic pod information
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
# ConfigMap access for configuration
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
# Secret access for credentials
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
# Service discovery
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list", "watch"]
# Events for logging
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: claude-conductor-orchestrator
  labels:
    app.kubernetes.io/name: claude-conductor
    app.kubernetes.io/component: orchestrator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: claude-conductor-orchestrator
subjects:
- kind: ServiceAccount
  name: claude-conductor
  namespace: claude-conductor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: claude-conductor-agent
  labels:
    app.kubernetes.io/name: claude-conductor
    app.kubernetes.io/component: agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: claude-conductor-agent
subjects:
- kind: ServiceAccount
  name: claude-conductor-agent
  namespace: claude-conductor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: claude-conductor-namespace
  namespace: claude-conductor
  labels:
    app.kubernetes.io/name: claude-conductor
rules:
# Full access within the namespace
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["networking.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: claude-conductor-namespace
  namespace: claude-conductor
  labels:
    app.kubernetes.io/name: claude-conductor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: claude-conductor-namespace
subjects:
- kind: ServiceAccount
  name: claude-conductor
  namespace: claude-conductor
- kind: ServiceAccount
  name: claude-conductor-agent
  namespace: claude-conductor