# Orchestrator configuration
orchestrator:
  num_agents: 3
  max_workers: 10
  task_timeout: 300
  log_level: INFO

# Agent configuration
agent:
  container_memory: "2g"
  container_cpu: "1.0"
  health_check_interval: 30
  startup_timeout: 60

# Communication settings
communication:
  socket_path: "/tmp/claude_orchestrator.sock"
  message_timeout: 5.0
  retry_count: 3

# Task queue settings
task_queue:
  max_size: 1000
  priority_levels: 10